-- Structured IV recommendation rules are presentation inputs, not individual Pokémon records.
CREATE TABLE "IvRecommendation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "scopeType" TEXT NOT NULL,
    "scopeKey" TEXT NOT NULL,
    "primaryUseKey" TEXT NOT NULL,
    "ivStrategyKey" TEXT NOT NULL,
    "maxBattleRole" TEXT,
    "attackIvMin" INTEGER,
    "attackIvPriority" INTEGER,
    "attackIvConditionalMin" INTEGER,
    "secondaryAttackIv" INTEGER,
    "defenseIvMin" INTEGER,
    "defenseIvPriority" INTEGER,
    "staminaIvMin" INTEGER,
    "staminaIvPriority" INTEGER,
    "totalIvPercentMin" REAL,
    "totalIvPercentPriority" REAL,
    "secondaryTotalIvPercentMin" REAL,
    "pvpRankMax" INTEGER,
    "pvpRankConditionalMax" INTEGER,
    "pvpPrMin" REAL,
    "recommendedQuantity" INTEGER,
    "hundoPriority" BOOLEAN NOT NULL DEFAULT false,
    "appliesOnlyWhenUseConfirmed" BOOLEAN NOT NULL DEFAULT true,
    "speciesSpecificOverride" BOOLEAN NOT NULL DEFAULT false,
    "overrideReasonZhTw" TEXT NOT NULL DEFAULT '',
    "ivRecommendationZhTw" TEXT NOT NULL,
    "shortIvLabelZhTw" TEXT NOT NULL,
    "rulesVersion" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

CREATE UNIQUE INDEX "IvRecommendation_scopeType_scopeKey_primaryUseKey_key"
ON "IvRecommendation"("scopeType", "scopeKey", "primaryUseKey");

CREATE INDEX "IvRecommendation_scopeType_scopeKey_idx"
ON "IvRecommendation"("scopeType", "scopeKey");

INSERT INTO "IvRecommendation" (
  "id", "scopeType", "scopeKey", "primaryUseKey", "ivStrategyKey", "maxBattleRole",
  "attackIvMin", "attackIvPriority", "attackIvConditionalMin", "secondaryAttackIv",
  "defenseIvMin", "defenseIvPriority", "staminaIvMin", "staminaIvPriority",
  "totalIvPercentMin", "totalIvPercentPriority", "secondaryTotalIvPercentMin",
  "pvpRankMax", "pvpRankConditionalMax", "pvpPrMin", "recommendedQuantity",
  "hundoPriority", "appliesOnlyWhenUseConfirmed", "speciesSpecificOverride",
  "overrideReasonZhTw", "ivRecommendationZhTw", "shortIvLabelZhTw", "rulesVersion", "updatedAt"
) VALUES
('iv-global-pve', 'GLOBAL', 'GLOBAL', 'PVE', 'PVE_ATTACKER', NULL,
 15, 15, NULL, 14, NULL, NULL, NULL, NULL, 91.1, 95.6, 95.6, NULL, NULL, NULL, NULL,
 false, true, false, '',
 '具有明確 PvE 用途時：15攻／96%以上優先；15攻／91%以上可留；14攻／96%以上為次選。低於91%或攻擊13以下，不能只靠IV成為保留理由。',
 'PvE：15攻／96%+', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-mega', 'GLOBAL', 'GLOBAL', 'MEGA', 'MEGA_ATTACKER', NULL,
 15, 15, NULL, 14, NULL, NULL, NULL, NULL, 91.1, 95.6, 95.6, NULL, NULL, NULL, 1,
 false, true, false, '',
 '具有重要 Mega 用途時：15攻／96%以上優先；15攻／91%以上可先留。通常只需保留一隻主要候選。',
 'Mega：15攻／96%+', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-master', 'GLOBAL', 'GLOBAL', 'MASTER_LEAGUE', 'MASTER_LEAGUE', NULL,
 15, 15, NULL, NULL, NULL, NULL, NULL, NULL, 95.6, 97.8, NULL, NULL, NULL, NULL, NULL,
 true, true, false, '',
 '具有大師聯盟用途時：15攻／96%以上為一般候選，15攻／98%以上優先，100%最優先；仍需確認該物種的特定攻防門檻。',
 'ML：15攻／98%優先', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-great', 'GLOBAL', 'GLOBAL', 'GREAT_LEAGUE', 'GREAT_LEAGUE_RANK', NULL,
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, 200, 97.5, NULL,
 false, true, false, '',
 '只有物種與目標進化結果確實具有超級聯盟用途時，個體 PvP IV Rank≤100或PR≥97.5%優先；Rank 101～200條件式。',
 'GL：Rank≤100', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-ultra', 'GLOBAL', 'GLOBAL', 'ULTRA_LEAGUE', 'ULTRA_LEAGUE_RANK', NULL,
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 100, 200, 97.5, NULL,
 false, true, false, '',
 '只有物種與目標進化結果確實具有高級聯盟用途時，個體 PvP IV Rank≤100或PR≥97.5%優先；Rank 101～200條件式。',
 'UL：Rank≤100', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-shadow-pve', 'GLOBAL', 'GLOBAL', 'SHADOW_PVE', 'SHADOW_PVE', NULL,
 13, 15, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 false, true, false, '',
 '具有明確暗影 PvE 價值時：15攻優先；攻擊13以上建議保留；攻擊10～12依稀有度、替代品、招式與既有投入條件式保留。攻擊低於10也不得自動傳送或淨化。',
 '暗影：攻擊13+，15優先', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-gym', 'GLOBAL', 'GLOBAL', 'GYM_DEFENSE', 'GYM_DEFENDER', NULL,
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1,
 false, true, false, '',
 '道館防守不設固定IV門檻；同物種比較時，優先已高等級、高CP及較高防禦／HP的候選。',
 '道館：無固定門檻', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-max-attack', 'GLOBAL', 'GLOBAL', 'MAX_ATTACK', 'MAX_ATTACKER', 'ATTACKER',
 NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 false, true, false, '',
 '已確認為 Max Battle 攻擊角色時，攻擊IV 15優先；不以單一總IV門檻取代角色與招式判斷。',
 'Max攻擊：15攻優先', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-max-tank', 'GLOBAL', 'GLOBAL', 'MAX_TANK', 'MAX_TANK', 'TANK',
 NULL, NULL, NULL, NULL, NULL, 15, NULL, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 false, true, false, '',
 '已確認為 Max Battle 坦克角色時，優先比較防禦IV、HP IV與整體耐久，不使用攻擊手的總IV門檻。',
 'Max坦克：防禦／HP優先', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-max-support', 'GLOBAL', 'GLOBAL', 'MAX_SUPPORT', 'MAX_SUPPORT', 'SUPPORT',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 false, true, false, '',
 'Max Battle 支援角色需依物種、耐久與Max招式建立專屬門檻，不套用統一15攻／96%條件。',
 'Max支援：依角色門檻', '2026.07.18-iv-v1', CURRENT_TIMESTAMP),
('iv-global-max-flex', 'GLOBAL', 'GLOBAL', 'MAX_FLEX', 'MAX_FLEX', 'FLEX',
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
 false, true, false, '',
 'Max Battle 角色尚未細分時，應分別確認攻擊、坦克或支援用途，不套用單一總IV門檻。',
 'Max：依角色分開', '2026.07.18-iv-v1', CURRENT_TIMESTAMP);
